### ISSUE TITLE
Please Add Nethunter Support !!!

### ISSUE THREAD

**Issue by L4FeeR** [TenSeventy7/android_kernel_samsung_exynos9610_fresh#10]
Respected sir, 

              I kindly request you to add Nethunter stuff such as HID, RNDIS, RTL8188EU, etc on this kernel, and also please release three edition,

  1.Normal Nethunterized + Default Magisk kernel.
   2. For AOSP Supported version.
   3. Overclocked kernel.
   
Please concern my request and build.
Thanking you

**Comment by TenSeventy7** [comment]
Hi!

1. Mint is designed to be a "daily-use" kernel and as such, developer features such as NetHunter are not planned to be added to the kernel, as this is additional overhead (affecting performance) and may be a security issue for most folks. I absolutely recommend forking this kernel and just adding NetHunter and compiling it yourself.
2. **AOSP support is already available since Mint 11.5.** Check the Releases page. :>
3. Overclocking is planned, but is currently not a priority due to work being done to support **One UI 4**. Stay tuned!

**Comment by TenSeventy7** [comment]
Closing due to lack of response.
